# Generated by Django 4.2.4 on 2023-08-29 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('show_last_seen', models.BooleanField(default=True, verbose_name='Show Last Seen')),
                ('show_read_receipts', models.BooleanField(default=True, help_text='Show Read Receipts in Private Chats', verbose_name='Show Read Receipts')),
                ('allow_to_add_groups', models.BooleanField(default=True, verbose_name='Allow to Add Groups')),
                ('allow_private_messages_to_non_contacts', models.BooleanField(default=True, verbose_name='Allow Private Messages to Non Contacts')),
                ('push_notifications_enabled', models.BooleanField(default=True, verbose_name='Push Notifications Enabled')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Account Settings',
                'verbose_name_plural': 'Account Settings',
                'db_table': 'account_settings',
            },
        ),
    ]
