# Generated by Django 4.2.4 on 2023-11-07 17:59

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 100 characters or fewer. Letters, digits and a-z,A-Z,0-9_ only.', max_length=100, unique=True, validators=[apps.accounts.models.UserNameValidator()], verbose_name='username'),
        ),
    ]
