# Generated by Django 4.2.4 on 2023-11-08 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('code_type', models.CharField(choices=[('general', 'General'), ('register', 'Register')], default='general', max_length=20, verbose_name='Code Type')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                ('expire_at', models.DateTimeField(verbose_name='Expire At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_codes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Confirmation Code',
                'verbose_name_plural': 'User Confirmation Codes',
                'db_table': 'user_confirmation_code',
            },
        ),
    ]
