# Generated by Django 4.2.4 on 2023-11-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userconfirmationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmationcode',
            name='token',
            field=models.CharField(default='8cK3pD71vTbhS7kHdD-IWKlT04_w-7j3e3P5uwoP', max_length=255, unique=True, verbose_name='Token'),
        ),
    ]
