# Generated by Django 4.2.4 on 2023-11-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userconfirmationcode_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmationcode',
            name='code',
            field=models.CharField(default='Klxr', max_length=6, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='userconfirmationcode',
            name='token',
            field=models.CharField(default='uXkBUF0F0Hoa2n0eUl1ojpn8kxQO-TwvVuzbfBHd', max_length=255, unique=True, verbose_name='Token'),
        ),
    ]
