# Generated by Django 4.2.4 on 2023-11-08 18:07

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userconfirmationcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmationcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='userconfirmationcode',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=255, unique=True, verbose_name='Token'),
        ),
    ]
