# Generated by Django 4.2.4 on 2023-11-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userconfirmationcode_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted?'),
        ),
        migrations.AddField(
            model_name='userconfirmationcode',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='userconfirmationcode',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted?'),
        ),
    ]
