# Generated by Django 4.2.4 on 2023-12-08 06:29

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_accountsettings_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmationcode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Attempts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=apps.accounts.models.default_username, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 100 characters or fewer. Letters, digits and a-z,A-Z,0-9_ only.', max_length=100, unique=True, validators=[apps.accounts.models.UserNameValidator()], verbose_name='username'),
        ),
    ]
