# Generated by Django 4.2.4 on 2023-12-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmationcode',
            name='code_type',
            field=models.CharField(choices=[('general', 'General'), ('register', 'Register'), ('reset_password', 'Reset password')], default='general', max_length=20, verbose_name='Code Type'),
        ),
    ]
