version: '3.8'

services:
  django:
    build:
      context: .
    container_name: ${COMPOSE_PROJECT_NAME}_django
    volumes:
      - ./:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - locale_volume:/app/locale
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: gunicorn core.wsgi:application --bind 0.0.0.0:${DJANGO_PORT}
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    restart: always

  postgres:
    image: postgres
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:6.0-bullseye
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: always

  daphne:
    build:
      context: .
    container_name: ${COMPOSE_PROJECT_NAME}_daphne
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - django
    command: daphne --port ${DAPHNE_PORT} core.asgi:application
    ports:
      - ${DAPHNE_PORT}:${DAPHNE_PORT}
    restart: always

volumes:
  postgres_data: {}
  static_volume: {}
  media_volume: {}
  locale_volume: {}
