# Generated by Django 4.2.4 on 2023-11-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted?'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted?'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted?'),
        ),
        migrations.AddField(
            model_name='posttag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='posttag',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted?'),
        ),
        migrations.AddField(
            model_name='tag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted?'),
        ),
    ]
