name: CD for shlyuz backend

on:
  workflow_run:
    workflows:
      - "Ci for shlyuz backend"
      - master
    types:
      - completed

jobs:
  deploy:
    name: Deploy to production
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: echo
        run: echo ${{ env.PROJECT_HOME }} && cd && ls
#      - name: cd & git pull
#        run: cd ${{ env.PROJECT_HOME }} && git pull
#      - name: Docker build for test
#        run: docker compose -f test.yml build
#      - name: Docker up for test
#        run: docker compose -f test.yml up -d
#      - name: Docker down for test
#        run: docker compose -f test.yml down -v
