name: Ci for shlyuz backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  execute_tests:
    name: Install requirements and run tests
    runs-on: self-hosted
    steps:
      - name: Update
        run: sudo apt-get update
      - name: Checkout
        uses: actions/checkout@v3
      - name: TEST
        run: pwd && ls -alh
