name: Ci for shlyuz backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  execute_tests:
    name: Install requirements and run tests
    runs-on: self-hosted
    steps:
      - name: Update
        run: sudo apt-get update
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pip
        run: sudo apt-get install python3-pip
      - name: Install requirements
        run: pip install --upgrade pip && pwd
