# Generated by Django 4.2.4 on 2023-09-05 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_message_is_reacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatmembership',
            name='interlocutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interlocutor_private_chat_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Interlocutor'),
        ),
    ]
