# Generated by Django 4.2.4 on 2023-09-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_privatechatmembership_interlocutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatmembership',
            name='interlocutor',
        ),
    ]
