# Generated by Django 4.2.4 on 2023-09-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_privatechatmembership_interlocutor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
