# Generated by Django 4.2.4 on 2023-12-08 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_chatmembership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='privatechatmembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='privatechatmembership',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='privatechatmembership',
            name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat', verbose_name='Chat'),
        ),
        migrations.DeleteModel(
            name='ChannelSubscription',
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
        migrations.DeleteModel(
            name='PrivateChatMembership',
        ),
    ]
